/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SessionRouteImport } from './routes/session'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RoutinesIndexRouteImport } from './routes/routines.index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises.index'
import { Route as RoutinesNewRouteImport } from './routes/routines.new'
import { Route as ExercisesExerciseIdRouteImport } from './routes/exercises.$exerciseId'
import { Route as RoutinesRoutineIdEditRouteImport } from './routes/routines.$routineId.edit'

const SessionRoute = SessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesIndexRoute = RoutinesIndexRouteImport.update({
  id: '/routines/',
  path: '/routines/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesNewRoute = RoutinesNewRouteImport.update({
  id: '/routines/new',
  path: '/routines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesExerciseIdRoute = ExercisesExerciseIdRouteImport.update({
  id: '/exercises/$exerciseId',
  path: '/exercises/$exerciseId',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutinesRoutineIdEditRoute = RoutinesRoutineIdEditRouteImport.update({
  id: '/routines/$routineId/edit',
  path: '/routines/$routineId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/session': typeof SessionRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/new': typeof RoutinesNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/routines/$routineId/edit': typeof RoutinesRoutineIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/session': typeof SessionRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/new': typeof RoutinesNewRoute
  '/exercises': typeof ExercisesIndexRoute
  '/routines': typeof RoutinesIndexRoute
  '/routines/$routineId/edit': typeof RoutinesRoutineIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/history': typeof HistoryRoute
  '/session': typeof SessionRoute
  '/exercises/$exerciseId': typeof ExercisesExerciseIdRoute
  '/routines/new': typeof RoutinesNewRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/routines/': typeof RoutinesIndexRoute
  '/routines/$routineId/edit': typeof RoutinesRoutineIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/history'
    | '/session'
    | '/exercises/$exerciseId'
    | '/routines/new'
    | '/exercises/'
    | '/routines/'
    | '/routines/$routineId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/history'
    | '/session'
    | '/exercises/$exerciseId'
    | '/routines/new'
    | '/exercises'
    | '/routines'
    | '/routines/$routineId/edit'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/history'
    | '/session'
    | '/exercises/$exerciseId'
    | '/routines/new'
    | '/exercises/'
    | '/routines/'
    | '/routines/$routineId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  HistoryRoute: typeof HistoryRoute
  SessionRoute: typeof SessionRoute
  ExercisesExerciseIdRoute: typeof ExercisesExerciseIdRoute
  RoutinesNewRoute: typeof RoutinesNewRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  RoutinesIndexRoute: typeof RoutinesIndexRoute
  RoutinesRoutineIdEditRoute: typeof RoutinesRoutineIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/session': {
      id: '/session'
      path: '/session'
      fullPath: '/session'
      preLoaderRoute: typeof SessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/': {
      id: '/routines/'
      path: '/routines'
      fullPath: '/routines/'
      preLoaderRoute: typeof RoutinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/new': {
      id: '/routines/new'
      path: '/routines/new'
      fullPath: '/routines/new'
      preLoaderRoute: typeof RoutinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/$exerciseId': {
      id: '/exercises/$exerciseId'
      path: '/exercises/$exerciseId'
      fullPath: '/exercises/$exerciseId'
      preLoaderRoute: typeof ExercisesExerciseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routines/$routineId/edit': {
      id: '/routines/$routineId/edit'
      path: '/routines/$routineId/edit'
      fullPath: '/routines/$routineId/edit'
      preLoaderRoute: typeof RoutinesRoutineIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  HistoryRoute: HistoryRoute,
  SessionRoute: SessionRoute,
  ExercisesExerciseIdRoute: ExercisesExerciseIdRoute,
  RoutinesNewRoute: RoutinesNewRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  RoutinesIndexRoute: RoutinesIndexRoute,
  RoutinesRoutineIdEditRoute: RoutinesRoutineIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
