import type { FretRange } from '@jazz-master/theory'
import { phrase, tab } from '../authoring'
import type { Exercise } from '../types'

/*
 * Every line here was written for this pack, in the manner of its style. None
 * is transcribed from a recording: changes, scales and idioms are common
 * property, but a player's solo is theirs.
 */

const FOUR_PASSES = { kind: 'repetitions', count: 4 } as const
const SIX_PASSES = { kind: 'repetitions', count: 6 } as const
const FIFTH: FretRange = { min: 5, max: 9 }
const BOX_ONE: FretRange = { min: 5, max: 8 }
const OPEN: FretRange = { min: 0, max: 4 }

/** Lines that come before the founding bebop line in the list: the same cadence, more plainly. */
export const LINES_BEFORE_BEBOP_LINE: readonly Exercise[] = [
  {
    id: 'lines-ii-v-i-c-chord-tones',
    title: 'Dm7 – G7 – Cmaj7 — a line of chord tones',
    area: 'lines',
    level: 1,
    key: 'C',
    styles: ['jazz'],
    contexts: ['major-ii-V-I'],
    feel: 'swing-8',
    about: [
      'Quarter notes, chord tones only: D–F–A–C over Dm7, then B–D–G–F over G7, then E, the third of C. It is not much of a melody, and that is the point — you can hear each chord in it with no accompaniment at all.',
      'Watch the joins. C at the end of bar one steps down to B, the third of G7; F at the end of bar two steps down to E, the third of Cmaj7. A line that lands on the third of each new chord always sounds like the changes.',
    ],
    tempoBpm: 100,
    duration: FOUR_PASSES,
    notes: phrase('D3:1 F3:1 A3:1 C4:1 | B3:1 D4:1 G4:1 F4:1 | E4:1 G4:1 B4:1 G4:1 | C5:4', { min: 4, max: 8 }),
  },
]

export const LINES_AFTER_BEBOP_LINE: readonly Exercise[] = [
  {
    id: 'lines-ii-v-i-c-enclosures',
    title: 'Dm7 – G7♭9 – Cmaj7 — enclosures and a flat nine',
    area: 'lines',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop'],
    contexts: ['major-ii-V-I'],
    feel: 'swing-8',
    about: [
      'Two devices in one line. Each new chord is entered through an enclosure: C and A♯ wrap around B, the third of G7; F and D♯ wrap around E, the third of Cmaj7. And over G7 the arpeggio runs B–D–F–A♭ — a diminished seventh chord from the third, which puts the flat ninth on top.',
      'Play it straight first, then swing it: long-short eighths, with the accent on the off-beat.',
    ],
    tempoBpm: 96,
    duration: FOUR_PASSES,
    notes: phrase('F4 A4 C5 A4 F4 D4 C4 A#3 | B3 D4 F4 Ab4 G4 F4 D4 D#4 | E4 G4 B4 D5 C5 A4 G4 E4 | C4:4', { min: 7, max: 10 }),
  },
  {
    id: 'lines-minor-ii-v-i',
    title: 'Bm7♭5 – E7♭9 – Am — a minor ii–V–i line',
    area: 'lines',
    level: 3,
    key: 'C',
    tonic: 'A',
    styles: ['jazz/bebop'],
    contexts: ['minor-ii-V-i'],
    feel: 'swing-8',
    about: [
      'Up the half-diminished arpeggio, then over E7 the same move as in the major key — the diminished arpeggio from the third, G♯–B–D–F — and down the A harmonic minor scale to the root. The last two notes before home are B and G♯: one above, one below.',
    ],
    tempoBpm: 92,
    duration: FOUR_PASSES,
    notes: phrase('B3 D4 F4 A4 C5 B4 A4 F4 | G#4 B4 D5 F5 E5 D5 C5 B4 | A4 B4 C5 E5 D5 C5 B4 G#4 | A4:4', { min: 9, max: 13 }),
  },
  {
    id: 'lines-turnaround',
    title: 'Cmaj7 – A7 – Dm7 – G7 — a turnaround line',
    area: 'lines',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop', 'jazz/swing'],
    contexts: ['turnaround'],
    feel: 'swing-8',
    about: [
      'Two beats a chord, twice round. With so little time the line just names each chord — up one arpeggio, down the next — and lets the odd notes out do the work: C♯ over A7, leading to D; B♭, its flat ninth, the second time.',
    ],
    tempoBpm: 96,
    duration: FOUR_PASSES,
    notes: phrase('C4 E4 G4 B4 Bb4 G4 E4 C#4 | D4 F4 A4 C5 B4 G4 F4 D4 | G4 E4 D4 C4 C#4 E4 G4 Bb4 | A4 F4 E4 D4 F4 D4 B3 D4 | C4:4', FIFTH),
  },
  {
    id: 'lines-tritone-substitution',
    title: 'Dm7 – D♭7 – Cmaj7 — the tritone substitute',
    area: 'lines',
    level: 4,
    key: 'C',
    styles: ['jazz/bebop'],
    contexts: ['substitution', 'major-ii-V-I'],
    feel: 'swing-8',
    about: [
      'G7 replaced by the dominant chord a tritone away. D♭7 has the same third and seventh as G7 — F and B — so it does the same job, while the bass slides down by half steps: D, D♭, C.',
      'The line simply plays D♭7 where G7 would be. Only F and B in that bar belong to C major — the two notes the chords share — and the step from E♭ up to E on the downbeat sets the rest right again.',
    ],
    tempoBpm: 92,
    duration: FOUR_PASSES,
    notes: phrase('D4 F4 A4 C5 A4 F4 E4 D4 | Db4 F4 Ab4 B4 Bb4 Ab4 F4 Eb4 | E4 G4 B4 C5 B4 G4 E4 D4 | C4:4', FIFTH),
  },
  {
    id: 'lines-backdoor',
    title: 'Fm7 – B♭7 – Cmaj7 — the backdoor ii–V',
    area: 'lines',
    level: 4,
    key: 'C',
    styles: ['jazz', 'jazz/swing'],
    contexts: ['substitution'],
    feel: 'swing-8',
    about: [
      'Instead of arriving at C from G7, arrive from B♭7 — through the back door. The chords come from C minor, so the line borrows A♭ and B♭, and the resolution is a whole step up, D to E, rather than the usual half step down. Warmer and less final than the front door.',
    ],
    tempoBpm: 92,
    duration: FOUR_PASSES,
    notes: phrase('F3 Ab3 C4 Eb4 D4 C4 Bb3 Ab3 | D4 F4 Ab4 C5 Bb4 Ab4 F4 D4 | E4 G4 B4 A4 G4 E4 D4 B3 | C4:4', FIFTH),
  },
  ...[
    {
      n: 1,
      source: 'B3 Eb4 F4 Ab4 Bb4 Ab4 F4 Eb4 | E4 G4 C5:3',
      about: 'From the third of G7 up through ♯5, flat seventh, ♭9 and ♯9, and back. The last altered note, E♭, rises a half step to E — the third of C — and the tension lets go.',
    },
    {
      n: 2,
      source: 'Ab4 G4 F4 Eb4 Db4 B3 Bb3 Ab3 | G3:1 C4:1 E4:2',
      about: 'Straight down the altered scale from the flat ninth. A♭ at the bottom falls a half step to G, and the C triad opens out from there.',
    },
  ].map(({ n, source, about }): Exercise => ({
    id: `lines-altered-cell-${n}`,
    title: `G7alt – C — altered resolution ${n}`,
    area: 'lines',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop', 'jazz/fusion'],
    contexts: ['major-ii-V-I'],
    feel: 'swing-8',
    series: 'altered-resolutions',
    about: [about, 'A one-bar cell and its landing. Short enough to memorise, transpose, and drop into any V–I you meet.'],
    tempoBpm: 84,
    duration: SIX_PASSES,
    notes: phrase(source, FIFTH),
  })),
  {
    id: 'lines-bebop-scale-descending',
    title: 'G7 – C — down the bebop scale',
    area: 'lines',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop'],
    contexts: ['major-ii-V-I'],
    feel: 'swing-8',
    about: [
      'Down the G bebop dominant scale from the root: G, F♯, F, E, D, C, B, A. Count what falls on the beats — G, F, D, B, the four notes of G7. The passing F♯ is there purely to make that happen.',
      'The second bar turns around through the arpeggio and lands on C.',
    ],
    tempoBpm: 96,
    duration: FOUR_PASSES,
    notes: phrase('G4 F#4 F4 E4 D4 C4 B3 A3 | G3 A3 B3 D4 F4 E4 D4 B3 | C4:4', { min: 2, max: 6 }),
  },
  {
    id: 'lines-jazz-blues-phrases',
    title: 'F7 — blues scale meets Mixolydian',
    area: 'lines',
    level: 2,
    key: 'F',
    styles: ['jazz/blues', 'jazz/swing', 'blues'],
    contexts: ['jazz-blues', '12-bar-blues'],
    feel: 'swing-8',
    about: [
      'Four bars over F7 built on one idea: A♭, the minor third, sliding up to A, the major third. The blues scale supplies the first note and the chord supplies the second, and the rub between them is the sound of jazz blues.',
    ],
    tempoBpm: 100,
    duration: FOUR_PASSES,
    notes: phrase('F4:1 Ab4 A4 C5 A4 F4:1 | D4 F4 Ab4 A4 F4:1 Eb4 D4 | C4 D4 Eb4 E4 F4 A4 C5 A4 | F4:4', FIFTH),
  },
  {
    id: 'lines-gypsy-harmonic-minor',
    title: 'E7 – Am — a harmonic minor run',
    area: 'lines',
    level: 3,
    key: 'C',
    tonic: 'A',
    styles: ['jazz/gypsy'],
    contexts: ['minor-ii-V-i'],
    techniques: ['rest-stroke'],
    feel: 'swing-8',
    about: [
      'Up A harmonic minor from E — which is E Phrygian dominant — to F at the top, and back down to resolve on A. Over the V chord of a minor key this one scale does everything a gypsy jazz player needs.',
      'Rest strokes: a downstroke each time the line reaches a new string.',
    ],
    tempoBpm: 100,
    duration: FOUR_PASSES,
    notes: phrase('E4 F4 G#4 A4 B4 C5 D5 E5 | F5 E5 D5 C5 B4 A4 G#4 B4 | A4:4', { min: 9, max: 13 }),
  },
  {
    id: 'lines-dorian-fourths',
    title: 'Dm7 — a Dorian line in fourths',
    area: 'lines',
    level: 4,
    key: 'C',
    tonic: 'D',
    styles: ['jazz/modal'],
    contexts: ['modal-vamp'],
    about: [
      'Over one chord for a long time there are no changes to outline, so the interest has to come from shape. This line is made of stacked fourths — D–G–C, E–A–D — with steps to join them.',
    ],
    tempoBpm: 96,
    duration: FOUR_PASSES,
    notes: phrase('D4 G4 C5 G4 E4 A4 D5 A4 | C4 F4 B4 F4 D4 G4 C5 A4 | D4:4', { min: 7, max: 10 }),
  },
  {
    id: 'lines-pentatonic-superimposition',
    title: 'Dm7 — E minor pentatonic on top',
    area: 'lines',
    level: 4,
    key: 'C',
    tonic: 'D',
    styles: ['jazz/modal', 'jazz/fusion'],
    contexts: ['modal-vamp'],
    about: [
      'The pentatonic box you already know, played a whole step above the chord. Against D minor, E minor pentatonic gives E, G, A, B, D: the ninth, eleventh, fifth, thirteenth and root. Every colour note of Dorian is in it, and the third and seventh — the notes that would merely spell the chord — are not.',
      'Old fingering, new sound. The same trick works a fifth above the chord.',
    ],
    tempoBpm: 92,
    duration: FOUR_PASSES,
    notes: phrase('E4 G4 A4 B4 D5 B4 A4 G4 | E4 D4 B3 D4 E4 G4 A4:1 | D4:4', { min: 7, max: 10 }),
  },
  {
    id: 'lines-bossa-phrase',
    title: 'Dm7 – G7 – Cmaj7 — a bossa phrase',
    area: 'lines',
    level: 2,
    key: 'C',
    styles: ['jazz/bossa-latin'],
    contexts: ['major-ii-V-I'],
    feel: 'bossa',
    about: [
      'Straight eighths, not swung, and a rhythm that leans ahead: a dotted quarter, then a note pushed onto the "and" of two. Bossa melodies are mostly chord tones placed just off the beat — the syncopation does what chromatic notes do in bebop.',
    ],
    tempoBpm: 120,
    duration: FOUR_PASSES,
    notes: phrase('A4:1.5 F4 D4:1 E4:1 | F4:1.5 D4 B3:1 D4:1 | E4:1.5 G4 B4:2 | A4:1 G4:1 E4:2', FIFTH),
  },
  ...[
    {
      n: 1,
      source: 'E4 G4 A4 C5 A4 G4 E4:1 | D4 E4 G4 E4 D4 C4 A3:1',
      about: 'Up to the high C and back, then an answer that falls to the root. Two bars, question and answer: the basic sentence of the blues.',
    },
    {
      n: 2,
      source: 'A3 C4 D4 Eb4 E4 G4 A4:1 | G4 E4 Eb4 D4 C4 D4 A3:1',
      about: 'Through the blue note both ways — D, E♭, E going up, E, E♭, D coming down. It never stops on E♭; it passes through.',
    },
    {
      n: 3,
      source: 'A4:1 G4 E4 G4 A4 C5:1 | A4 G4 E4 D4 C4:1 A3:1',
      about: 'A held note, a turn around it, and a long fall. Leave the quarter notes their full length — space is half of blues phrasing.',
    },
  ].map(({ n, source, about }): Exercise => ({
    id: `lines-blues-box-one-lick-${n}`,
    title: `A blues — box 1 lick ${n}`,
    area: 'lines',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['blues', 'rock'],
    contexts: ['12-bar-blues'],
    series: 'blues-box-one-licks',
    about: [about, 'All of it sits inside box 1 of A minor pentatonic. On a real guitar the Gs and Ds would often be bent up a whole step from the note below; learn the notes first and add the bends when they are secure.'],
    tempoBpm: 84,
    duration: SIX_PASSES,
    notes: phrase(source, BOX_ONE),
  })),
  {
    id: 'lines-boogie-bass-riff',
    title: 'A boogie bass riff through twelve bars',
    area: 'lines',
    level: 1,
    key: 'D',
    tonic: 'A',
    styles: ['blues', 'rock'],
    contexts: ['12-bar-blues'],
    feel: 'shuffle',
    about: [
      'Root, third, fifth, sixth, flat seventh and back — the left hand of boogie-woogie piano moved to the low strings, one bar per chord through a blues in A. The shape is identical for A7, D7 and E7; only the string changes.',
      'Played with a shuffle it should lope rather than march: long-short, long-short.',
    ],
    tempoBpm: 116,
    duration: { kind: 'repetitions', count: 2 },
    notes: tab(
      ['5/0', '4/0', '5/0', '5/0', '4/0', '4/0', '5/0', '5/0', '6/0', '4/0', '5/0', '6/0']
        .map((root) => {
          const [string] = root.split('/')
          const next = Number(string) - 1
          return `${string}/0 ${string}/4 ${next}/2 ${next}/4 ${next}/5 ${next}/4 ${next}/2 ${string}/4`
        })
        .join(' | '),
    ),
  },
  {
    id: 'lines-rock-low-string-riff',
    title: 'E minor pentatonic — a low-string riff',
    area: 'lines',
    level: 1,
    styles: ['rock'],
    techniques: ['palm-mute'],
    key: 'G',
    tonic: 'E',
    about: [
      'Open low E as the anchor, with G, A and B♭ answering it: the pentatonic plus the flat fifth, down where it growls. Most classic rock riffs are some version of this — a pedal on the open string and two or three notes against it.',
      'Downstrokes throughout, the open E lightly muted with the edge of the hand.',
    ],
    tempoBpm: 88,
    duration: SIX_PASSES,
    notes: phrase('E2 E2 G2 E2 A2 E2 Bb2 A2 | E2 E2 G2 A2 B2 D3 E3:1', OPEN),
  },
  {
    id: 'lines-rock-repeating-lick',
    title: 'A minor pentatonic — a repeating lick',
    area: 'lines',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['rock', 'blues'],
    about: [
      'Four notes at the top of box 1, round and round. Repetition is a rock soloist\'s way of building tension: the phrase stays the same while the band moves underneath, until the release at the end of the second bar.',
    ],
    tempoBpm: 88,
    duration: SIX_PASSES,
    notes: phrase('A4 C5 A4 G4 A4 C5 A4 G4 | A4 C5 A4 G4 E4 G4 A4:1', BOX_ONE),
  },
  {
    id: 'lines-pedal-tone-riff',
    title: 'A minor — a melody over an open-string pedal',
    area: 'lines',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['rock', 'metal', 'folk-acoustic'],
    techniques: ['string-skipping', 'alternate'],
    about: [
      'Every other note is the open A string; the notes between walk down the scale. One guitar sounds like two parts — a drone and a tune — and the picking hand has to hop between them without the pedal getting louder than the melody.',
    ],
    tempoBpm: 84,
    duration: SIX_PASSES,
    notes: phrase('A2 A3 A2 G3 A2 F3 A2 E3 | A2 F3 A2 E3 A2 D3 E3:1', OPEN),
  },
  {
    id: 'lines-natural-minor-lead',
    title: 'A natural minor — a lead phrase',
    area: 'lines',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['rock', 'pop', 'metal'],
    techniques: ['vibrato'],
    about: [
      'Four bars that sing rather than run: long notes, a climb, and an arrival on the high A. The notes that make natural minor different from pentatonic — B and F — are the expressive ones here.',
      'Give every long note vibrato. A slow melody is where tone shows.',
    ],
    tempoBpm: 84,
    duration: FOUR_PASSES,
    notes: phrase('E4:1.5 D4 C4:1 B3 C4 | D4:1 E4 F4 E4:1 C4:1 | A3 B3 C4 E4 A4:1 G4 E4 | A4:4', { min: 4, max: 8 }),
  },
  {
    id: 'lines-metal-gallop-riff',
    title: 'E Phrygian — a galloping riff',
    area: 'lines',
    level: 2,
    styles: ['metal'],
    techniques: ['palm-mute', 'alternate'],
    feel: 'straight-16',
    key: 'C',
    tonic: 'E',
    about: [
      'The gallop rhythm put to work: open E, then F a half step above it — the Phrygian second, the darkest interval available — then G and back. Palm-mute everything and let only the last note ring.',
    ],
    tempoBpm: 88,
    duration: SIX_PASSES,
    notes: tab(
      '6/0 6/0:0.25*2 6/0 6/0:0.25*2 6/1 6/1:0.25*2 6/0 6/0:0.25*2 | 6/0 6/0:0.25*2 6/0 6/0:0.25*2 6/3 6/3:0.25*2 6/1 6/1:0.25*2 | 6/0:4',
    ),
  },
  {
    id: 'lines-neoclassical-pedal-point',
    title: 'A harmonic minor — a pedal-point lick',
    area: 'lines',
    level: 4,
    key: 'C',
    tonic: 'A',
    styles: ['metal', 'classical'],
    techniques: ['alternate'],
    feel: 'straight-16',
    about: [
      'A melody note, then A, then the next melody note, then A again: a baroque violin figure that metal guitarists adopted wholesale. The returning A is the pedal point; the notes against it trace harmonic minor, G♯ and all.',
      'Strict alternate picking. The pedal notes should be quieter than the melody notes.',
    ],
    tempoBpm: 66,
    duration: FOUR_PASSES,
    notes: phrase('C5 A4 B4 A4 C5 A4 D5 A4 E5 A4 D5 A4 C5 A4 B4 A4 | C5 A4 B4 A4 G#4 A4 B4 A4 C5 A4 B4 A4 A4:1', { min: 9, max: 13 }, 0.25),
  },
  {
    id: 'lines-funk-sixteenths',
    title: 'Em7 — a sixteenth-note funk line',
    area: 'lines',
    level: 3,
    key: 'D',
    tonic: 'E',
    styles: ['funk-soul', 'jazz/fusion'],
    contexts: ['modal-vamp'],
    techniques: ['alternate'],
    feel: 'straight-16',
    about: [
      'Two bars of E minor pentatonic in running sixteenths, the flat fifth passing through: the kind of single-note part a funk guitarist doubles with the bass. The difficulty is entirely in the right hand.',
      'Keep the picking hand moving down-up in sixteenths whether or not it is playing, and accent the first note of each beat. Short, dry notes: lift the fretting fingers the moment each note has sounded.',
    ],
    tempoBpm: 76,
    duration: FOUR_PASSES,
    notes: phrase('E3 G3 A3 Bb3 B3 D4 E4 D4 B3 A3 G3 A3 B3 D4 E4 G4 | A4 G4 E4 D4 E4 D4 B3 A3 G3 A3 B3 G3 E3:1', FIFTH, 0.25),
  },
  {
    id: 'lines-country-major-pentatonic',
    title: 'G — a country lick from minor third to major',
    area: 'lines',
    level: 2,
    key: 'G',
    styles: ['country', 'country/bluegrass'],
    contexts: ['I-IV-V'],
    techniques: ['slides', 'hybrid'],
    about: [
      'G major pentatonic with one extra note: B♭, which exists only to slide up into B. That half step, minor third to major third, is to country guitar what the blue note is to blues.',
      'Up to the high G and back down to the low one. Slide the B♭ into B with one finger.',
    ],
    tempoBpm: 88,
    duration: SIX_PASSES,
    notes: phrase('G3 A3 Bb3 B3 D4 E4 G4:1 | E4 D4 B3 A3 G3 E3 G3:1', { min: 2, max: 5 }),
  },
  {
    id: 'lines-bluegrass-g-run',
    title: 'The G run, and a fiddle-tune phrase',
    area: 'lines',
    level: 3,
    key: 'G',
    styles: ['country/bluegrass', 'folk-acoustic'],
    techniques: ['alternate'],
    about: [
      'The G run is the bluegrass guitarist\'s punctuation mark: low G up through B♭ and B to the open G string, played at the end of a line to say "there". After it, three bars in the manner of a fiddle tune — all eighth notes, open strings wherever possible, and strict down-up picking so the downstrokes stay on the beat.',
    ],
    tempoBpm: 100,
    duration: FOUR_PASSES,
    notes: phrase('G2 A2 Bb2 B2 D3 E3 G3:1 | B3 D4 G4 D4 B3 D4 G4 D4 | E4 G4 E4 D4 B3 A3 G3 A3 | B3 G3 A3 F#3 G3:2', OPEN),
  },
  {
    id: 'lines-flamenco-picado',
    title: 'E Phrygian dominant — a picado run',
    area: 'lines',
    level: 3,
    key: 'C',
    tonic: 'E',
    styles: ['latin-flamenco'],
    contexts: ['andalusian-cadence'],
    techniques: ['fingerstyle'],
    feel: 'straight-16',
    about: [
      'Picado is the flamenco scale technique: index and middle fingers alternating, each coming to rest on the next string, for a sharp, percussive attack. The run falls from the open high E to the E an octave below, then climbs back — Phrygian with a major third, the scale of the E chord that ends the Andalusian cadence.',
      'With a pick, play it as strict alternate picking. Either way, every note detached and equal.',
    ],
    tempoBpm: 66,
    duration: FOUR_PASSES,
    notes: phrase('E4 F4 E4 D4 C4 D4 C4 B3 A3 B3 A3 G#3 F3 G#3 F3 E3 | F3 G#3 A3 B3 C4 D4 E4 F4 E4:2', OPEN, 0.25),
  },
  {
    id: 'lines-pop-hook',
    title: 'C major pentatonic — a singable hook',
    area: 'lines',
    level: 1,
    key: 'C',
    styles: ['pop'],
    contexts: ['I-V-vi-IV'],
    about: [
      'Five notes, mostly long, with the second half answering the first. A hook is a melody simple enough to remember after one hearing — writing one is harder than playing a fast scale, and playing one well is mostly a matter of tone and timing.',
      'Sing it while you play it. If you can sing it, you can phrase it.',
    ],
    tempoBpm: 96,
    duration: FOUR_PASSES,
    notes: phrase('E4:1 G4:1 A4 G4 E4:1 | D4:1 E4 D4 C4:2 | E4:1 G4:1 C5 A4 G4:1 | E4 D4 C4:3', BOX_ONE),
  },
]
