import type { FretRange } from '@jazz-master/theory'
import { closeOnBarLine, phrase, sequenceRun, tab } from '../authoring'
import type { Exercise } from '../types'

const SEVENTH: FretRange = { min: 7, max: 10 }
const BOX_ONE: FretRange = { min: 5, max: 8 }
const FOUR_PASSES = { kind: 'repetitions', count: 4 } as const

/** The 1-2-3-5 cell from a root on the fifth or sixth string: root and second on one string, third and fifth on the next. */
function digitalCell(string: 5 | 6, fret: number): string {
  const next = string - 1
  return `${string}/${fret} ${string}/${fret + 2} ${next}/${fret - 1} ${next}/${fret + 2}`
}

export const PATTERNS: readonly Exercise[] = [
  {
    id: 'patterns-one-note-everywhere',
    title: 'Every C on the neck',
    area: 'patterns',
    level: 1,
    techniques: ['position-shift'],
    series: 'fretboard-knowledge',
    about: [
      'One note, eight places. Knowing the neck means being able to put a finger on any note on any string without counting up from the nut — and the way there is dull and quick: find every C, then every F, then the rest, a note a day.',
      'Say "C" each time you land. The shape between neighbouring Cs — two strings up and two frets up is an octave — is what you are really memorising.',
    ],
    tempoBpm: 60,
    duration: FOUR_PASSES,
    notes: tab('5/3:2 6/8:2 | 4/10:2 3/5:2 | 2/1:2 1/8:2 | 2/13:2 3/17:2'),
  },
  {
    id: 'patterns-cycle-of-fourths-roots',
    title: 'Roots around the cycle of fourths',
    area: 'patterns',
    level: 1,
    contexts: ['cycle-of-fourths'],
    series: 'fretboard-knowledge',
    about: [
      'C, F, B♭, E♭, A♭, D♭, G♭, B, E, A, D, G and home: all twelve notes, each a fourth above the last, on the two lowest strings. Chords in real music move this way more than any other — every ii–V–I is three steps round this circle.',
      'Once the roots are automatic, practise anything through the cycle — a chord, an arpeggio, a lick — and you have practised it in every key.',
    ],
    tempoBpm: 60,
    duration: FOUR_PASSES,
    notes: tab('5/3:2 6/1:2 | 5/1:2 5/6:2 | 6/4:2 5/4:2 | 6/2:2 5/2:2 | 6/0:2 5/0:2 | 5/5:2 6/3:2 | 5/3:4'),
  },
  {
    id: 'patterns-thirds',
    title: 'C major in thirds',
    area: 'patterns',
    level: 2,
    key: 'C',
    contexts: ['diatonic'],
    series: 'major-scale-sequences',
    about: [
      'Up a third, back a step, up a third: C–E, D–F, E–G. Thirds are what chords are made of, so a scale in thirds is halfway to being a melody already — and it breaks the habit of only ever playing scales in a straight line.',
      'Some thirds are major and some minor, and the fingering changes accordingly. That unevenness is the scale\'s harmony showing through.',
    ],
    tempoBpm: 72,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 2]),
  },
  {
    id: 'patterns-fourths',
    title: 'C major in fourths',
    area: 'patterns',
    level: 3,
    key: 'C',
    styles: ['jazz/modal', 'jazz/fusion'],
    contexts: ['diatonic'],
    series: 'major-scale-sequences',
    about: [
      'Fourths sound open and modern where thirds sound sweet. On the guitar a fourth is usually the same fret on the next string, which means rolling one fingertip across two strings — the real technical content of this exercise.',
    ],
    tempoBpm: 66,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 3]),
  },
  {
    id: 'patterns-sixths',
    title: 'C major in sixths',
    area: 'patterns',
    level: 3,
    key: 'C',
    styles: ['country', 'funk-soul'],
    contexts: ['diatonic'],
    techniques: ['string-skipping'],
    series: 'major-scale-sequences',
    about: [
      'A sixth is a third turned upside down, and it is the widest interval that still sounds like harmony rather than a leap. Every pair skips a string, so the picking hand is working as hard as the ear.',
    ],
    tempoBpm: 63,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 5]),
  },
  {
    id: 'patterns-groups-of-three',
    title: 'C major in groups of three',
    area: 'patterns',
    level: 2,
    key: 'C',
    styles: ['rock'],
    series: 'major-scale-sequences',
    about: [
      'Three notes up, start again one step higher: C-D-E, D-E-F, E-F-G. In eighth notes the three-note group keeps shifting against the beat, so the accent lands on a different note of the group each time — keep the click where it is and let the pattern roll over it.',
    ],
    tempoBpm: 76,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 1, 2], { span: 10 }),
  },
  {
    id: 'patterns-groups-of-four',
    title: 'C major in groups of four',
    area: 'patterns',
    level: 2,
    key: 'C',
    styles: ['rock', 'metal'],
    series: 'major-scale-sequences',
    about: [
      'Four notes up, back three, four notes up. It fits the beat squarely, which makes it the sequence most often heard at speed in rock and metal solos. Clean at sixty is worth more than smeared at a hundred and twenty.',
    ],
    tempoBpm: 80,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 1, 2, 3], { span: 10 }),
  },
  {
    id: 'patterns-diatonic-triads',
    title: 'The triads of C major',
    area: 'patterns',
    level: 3,
    key: 'C',
    contexts: ['diatonic'],
    series: 'major-scale-sequences',
    about: [
      'A triad from every note of the scale: C, D minor, E minor, F, G, A minor, B diminished. These seven chords are the harmony of the key, and playing them as a line teaches the hand and the ear together which is major, which minor, and where the odd one lives.',
    ],
    tempoBpm: 72,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 2, 4], { span: 11 }),
  },
  {
    id: 'patterns-diatonic-sevenths',
    title: 'The seventh chords of C major',
    area: 'patterns',
    level: 3,
    key: 'C',
    styles: ['jazz'],
    contexts: ['diatonic'],
    series: 'major-scale-sequences',
    about: [
      'Four-note arpeggios from each scale degree: Cmaj7, Dm7, Em7, Fmaj7, G7, Am7, Bm7♭5. This is the harmonised major scale, the table every jazz chord progression is read from. Dm7, G7 and Cmaj7 — the ii, the V and the I — are all in here, in order.',
      'Name each chord as you start it.',
    ],
    tempoBpm: 72,
    duration: FOUR_PASSES,
    notes: sequenceRun('C', 'major', SEVENTH, [0, 2, 4, 6], { span: 13 }),
  },
  {
    id: 'patterns-pentatonic-threes',
    title: 'A minor pentatonic in groups of three',
    area: 'patterns',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['rock', 'blues'],
    series: 'pentatonic-sequences',
    about: [
      'Box 1 in threes. With only two notes on a string, every group crosses a string, so this is a picking exercise disguised as a lick — and it is a lick: played fast, this is one of the stock phrases of rock guitar.',
    ],
    tempoBpm: 80,
    duration: FOUR_PASSES,
    notes: sequenceRun('A', 'minorPentatonic', BOX_ONE, [0, 1, 2]),
  },
  {
    id: 'patterns-pentatonic-fours',
    title: 'A minor pentatonic in groups of four',
    area: 'patterns',
    level: 2,
    key: 'C',
    tonic: 'A',
    styles: ['rock', 'blues'],
    series: 'pentatonic-sequences',
    about: [
      'Four notes up, back three. Groups of four sit squarely on the beat, so use them to check that the first note of each group lands exactly with the click.',
    ],
    tempoBpm: 84,
    duration: FOUR_PASSES,
    notes: sequenceRun('A', 'minorPentatonic', BOX_ONE, [0, 1, 2, 3], { span: 10 }),
  },
  {
    id: 'patterns-pentatonic-skips',
    title: 'A minor pentatonic in skips',
    area: 'patterns',
    level: 4,
    key: 'C',
    tonic: 'A',
    styles: ['jazz/fusion', 'rock'],
    techniques: ['string-skipping'],
    series: 'pentatonic-sequences',
    about: [
      'Every other note of the pentatonic: mostly fourths and fifths, and nearly every pair on different strings. It takes the most familiar scale there is and makes it sound angular and modern, which is how fusion players get so much out of five notes.',
    ],
    tempoBpm: 66,
    duration: FOUR_PASSES,
    notes: sequenceRun('A', 'minorPentatonic', BOX_ONE, [0, 2]),
  },
  {
    id: 'patterns-stacked-fourths-dorian',
    title: 'Stacked fourths in D Dorian',
    area: 'patterns',
    level: 4,
    key: 'C',
    tonic: 'D',
    styles: ['jazz/modal'],
    contexts: ['modal-vamp'],
    about: [
      'Three notes a fourth apart, then the same from the next note of the mode. Stacks of fourths do not spell a chord the way thirds do, so they float over a D minor vamp without insisting on anything — the sound modal jazz has had since the early sixties.',
    ],
    tempoBpm: 66,
    duration: FOUR_PASSES,
    notes: sequenceRun('D', 'dorian', { min: 4, max: 8 }, [0, 3, 6], { span: 13 }),
  },
  {
    id: 'patterns-1235-cycle',
    title: '1-2-3-5 around the cycle of fourths',
    area: 'patterns',
    level: 3,
    styles: ['jazz/bebop'],
    contexts: ['cycle-of-fourths'],
    about: [
      'Root, second, third, fifth — four notes that state a major chord completely — played from each of the twelve roots in turn. Two beats per key: the cell is over before you can think, so it has to be in the fingers.',
      'One fingering does it all: root and second on one string, third and fifth on the next. Only the starting point moves.',
    ],
    tempoBpm: 84,
    duration: FOUR_PASSES,
    notes: tab(
      [
        digitalCell(5, 3), digitalCell(6, 1), digitalCell(5, 1), digitalCell(5, 6), digitalCell(6, 4), digitalCell(5, 4),
        digitalCell(6, 2), digitalCell(5, 2), digitalCell(5, 7), digitalCell(6, 5), digitalCell(5, 5), digitalCell(6, 3), '5/3:4',
      ].join(' '),
    ),
  },
  {
    id: 'patterns-chromatic-approach',
    title: 'Approach notes — a half step below each chord tone',
    area: 'patterns',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop', 'jazz/swing'],
    about: [
      'Every note of a C major triad, each reached from the note a half step beneath it. The approach notes are all outside the chord and some are outside the key; they sound right because of where they go and when they get there — off the beat, resolving onto it.',
      'This is the smallest unit of jazz phrasing. Any chord tone can be decorated this way.',
    ],
    tempoBpm: 76,
    duration: FOUR_PASSES,
    notes: closeOnBarLine(phrase('B3 C4 D#4 E4 F#4 G4 B4 C5 | B4 C5 F#4 G4 D#4 E4 B3 C4', SEVENTH)),
  },
  {
    id: 'patterns-enclosures',
    title: 'Enclosures — surrounding each chord tone',
    area: 'patterns',
    level: 3,
    key: 'C',
    styles: ['jazz/bebop'],
    about: [
      'The scale note above, the half step below, then the target: D–B–C, F–D♯–E, A–F♯–G. An enclosure delays a chord tone by circling it, and the delay is what makes the arrival satisfying. Bebop lines are full of them.',
      'Each group is three notes, so the target falls on a different part of the beat every time. Once it is comfortable, shift the whole thing by an eighth so the targets land on the beat.',
    ],
    tempoBpm: 72,
    duration: FOUR_PASSES,
    notes: closeOnBarLine(phrase('D4 B3 C4 F4 D#4 E4 A4 F#4 G4 D5 B4 C5 | A4 F#4 G4 F4 D#4 E4 D4 B3 C4', SEVENTH)),
  },
  {
    id: 'patterns-triad-pairs',
    title: 'Triad pairs — C and D over C Lydian',
    area: 'patterns',
    level: 5,
    key: 'G',
    tonic: 'C',
    styles: ['jazz/fusion', 'jazz/modal'],
    contexts: ['modal-vamp'],
    about: [
      'Two major triads a whole step apart share no notes, and between them make six of the seven notes of C Lydian. Alternating them — C, then D, each in its next inversion — gives a line that climbs in clear, strong shapes instead of running up a scale.',
      'It is a way of sounding organised while playing outside the usual patterns. Any two neighbouring triads of a scale will do; this pair is the brightest.',
    ],
    tempoBpm: 72,
    duration: FOUR_PASSES,
    notes: closeOnBarLine(phrase('C4 E4 G4 A4 D5 F#5 | E4 G4 C5 F#4 A4 D5 | G4 C5 E5 D5 A4 F#4 | E5 C5 G4 D5 A4 F#4 | C5 G4 E4 A4 F#4 D4 | C4:2', { min: 7, max: 14 })),
  },
]
