import type { GuitarString } from '@jazz-master/theory'
import { arpeggioRun, closeOnBarLine, tab, threePerStringRun } from '../authoring'
import type { Exercise, TabNote } from '../types'

/** One finger per fret across every string, in a fixed finger order, up the strings and mirrored back. */
function spider(fingers: readonly number[], startFret: (string: GuitarString) => number): TabNote[] {
  const strings: GuitarString[] = [6, 5, 4, 3, 2, 1]
  const up = strings.flatMap((string) => fingers.map((finger) => ({ string, fret: startFret(string) + finger - 1, beats: 0.5 })))
  return closeOnBarLine([...up, ...[...up].reverse()])
}

export const TECHNIQUE: readonly Exercise[] = [
  {
    id: 'technique-spider-1234',
    title: 'The spider — 1-2-3-4 across the strings',
    area: 'technique',
    level: 1,
    techniques: ['alternate'],
    series: 'spider',
    about: [
      'One finger per fret, frets five to eight, low string to high and back. There is no music in it on purpose: with nothing to listen for but evenness, you hear every weak finger and every late pick stroke.',
      'Strict alternate picking, down-up throughout, and leave each finger down until it has to move. Slow enough that all four notes on a string sound the same length and the same loudness.',
    ],
    tempoBpm: 60,
    duration: { kind: 'minutes', minutes: 2 },
    notes: spider([1, 2, 3, 4], () => 5),
  },
  {
    id: 'technique-spider-1324',
    title: 'The spider — 1-3-2-4',
    area: 'technique',
    level: 2,
    techniques: ['alternate'],
    series: 'spider',
    about: [
      'The same frets as the first spider, in the order 1-3-2-4. Breaking the row apart makes the second and third fingers move independently — the pair that most wants to move together.',
      'Keep the hand still and let only the fingers travel. If the fourth finger flies away from the neck between notes, slow down until it stays close.',
    ],
    tempoBpm: 60,
    duration: { kind: 'minutes', minutes: 2 },
    notes: spider([1, 3, 2, 4], () => 5),
  },
  {
    id: 'technique-spider-1423',
    title: 'The spider — 1-4-2-3',
    area: 'technique',
    level: 2,
    techniques: ['alternate'],
    series: 'spider',
    about: [
      'First to fourth finger is the widest reach in the position, and this order makes you take it on every string. On the way back the mirror image leads with the third finger, the weakest.',
    ],
    tempoBpm: 60,
    duration: { kind: 'minutes', minutes: 2 },
    notes: spider([1, 4, 2, 3], () => 5),
  },
  {
    id: 'technique-spider-diagonal',
    title: 'The spider — climbing a fret per string',
    area: 'technique',
    level: 2,
    techniques: ['alternate', 'position-shift'],
    series: 'spider',
    about: [
      'The 1-2-3-4 spider, but the whole hand moves up one fret each time it crosses to a new string, from the first fret on the low E to the sixth on the high E. It adds the one thing the fixed spider leaves out: shifting position without looking.',
      'Move the hand during the string change, not after it — the first finger should arrive with the pick.',
    ],
    tempoBpm: 60,
    duration: { kind: 'minutes', minutes: 2 },
    notes: spider([1, 2, 3, 4], (string) => 7 - string),
  },
  {
    id: 'technique-subdivisions',
    title: 'One note — quarters, eighths, sixteenths',
    area: 'technique',
    level: 1,
    techniques: ['alternate'],
    feel: 'straight-16',
    about: [
      'A single C, played a bar at a time as quarter notes, eighths, then sixteenths, and a whole note to breathe. The click never changes; only how many notes you fit between its beats.',
      'The join between bars is the exercise. Doubling the speed without rushing the first beat of the new bar is what playing in time means.',
    ],
    tempoBpm: 60,
    duration: { kind: 'repetitions', count: 6 },
    notes: tab('3/5:1*4 | 3/5*8 | 3/5:0.25*16 | 3/5:4'),
  },
  {
    id: 'technique-outside-picking',
    title: 'Two strings — outside picking',
    area: 'technique',
    level: 2,
    techniques: ['alternate'],
    series: 'string-crossing',
    about: [
      'Every note changes string. Start with a downstroke on the D string and the pick travels around the outside of the pair: down on the lower string, up on the higher. Most players find this the comfortable direction.',
      'Keep alternating no matter what. The point is to make the string change belong to the picking motion instead of interrupting it.',
    ],
    tempoBpm: 70,
    duration: { kind: 'repetitions', count: 6 },
    notes: closeOnBarLine(tab('4/5 3/5 4/7 3/7 4/8 3/8 4/7 3/7 | 4/5 3/5 4/7 3/7 4/8 3/8 4/7 3/7 | 4/5:4')),
  },
  {
    id: 'technique-inside-picking',
    title: 'Two strings — inside picking',
    area: 'technique',
    level: 2,
    techniques: ['alternate'],
    series: 'string-crossing',
    about: [
      'The outside-picking exercise turned over: it starts on the higher string, so a downstroke there is followed by an upstroke on the lower one and the pick is trapped between the two strings. This is the awkward direction, which is the reason to practise it.',
      'Start with a downstroke and do not let the hand cheat its way back to outside picking.',
    ],
    tempoBpm: 66,
    duration: { kind: 'repetitions', count: 6 },
    notes: closeOnBarLine(tab('3/5 4/5 3/7 4/7 3/8 4/8 3/7 4/7 | 3/5 4/5 3/7 4/7 3/8 4/8 3/7 4/7 | 3/5:4')),
  },
  {
    id: 'technique-octave-skips',
    title: 'String skipping — a scale in octaves',
    area: 'technique',
    level: 2,
    techniques: ['string-skipping', 'position-shift', 'alternate'],
    key: 'G',
    about: [
      'G major up the low E string, each note answered by its octave two strings over. The pick has to jump a string it must not touch, and the hand shifts along the neck with every step.',
      'The octave shape — two strings up, two frets up — is one of the most useful landmarks on the neck. Look at where the next low note is, not at the one you are playing.',
    ],
    tempoBpm: 70,
    duration: { kind: 'repetitions', count: 4 },
    notes: closeOnBarLine(
      tab('6/3 4/5 6/5 4/7 6/7 4/9 6/8 4/10 6/10 4/12 6/12 4/14 6/14 4/16 6/15 4/17 6/14 4/16 6/12 4/14 6/10 4/12 6/8 4/10 6/7 4/9 6/5 4/7 6/3 4/5'),
    ),
  },
  {
    id: 'technique-sixths-skips',
    title: 'String skipping — sixths up the G and high E strings',
    area: 'technique',
    level: 3,
    styles: ['country', 'blues', 'funk-soul'],
    techniques: ['string-skipping', 'position-shift', 'hybrid'],
    key: 'G',
    about: [
      'The G major scale harmonised in sixths, the lower note on the G string and the upper on the high E, played one after the other. Sixths on this string pair are the sound of country fills, soul rhythm parts and blues turnarounds.',
      'Two shapes cover the whole scale: a major sixth has both notes on the same fret, a minor sixth has the upper note one fret lower. Learn which degree of the scale gets which.',
      'With a pick alone it is a string-skipping drill. With pick and middle finger — pick the G string, pluck the E — it is the way these are usually played.',
    ],
    tempoBpm: 72,
    duration: { kind: 'repetitions', count: 4 },
    notes: closeOnBarLine(
      tab('3/4 1/3 3/5 1/5 3/7 1/7 3/9 1/8 3/11 1/10 3/12 1/12 3/14 1/14 3/16 1/15 3/14 1/14 3/12 1/12 3/11 1/10 3/9 1/8 3/7 1/7 3/5 1/5 3/4 1/3'),
    ),
  },
  {
    id: 'technique-economy-three-per-string',
    title: 'Economy picking — three notes per string',
    area: 'technique',
    level: 3,
    styles: ['rock', 'metal', 'jazz/fusion'],
    techniques: ['economy'],
    key: 'G',
    about: [
      'G major with three notes on every string. Going up, pick down-up-down and let the last downstroke fall through onto the next string as another downstroke: one motion, two strings. Coming down it is the mirror — up-down-up, and the upstroke carries across.',
      'The sweep across the string change must stay in time. Almost everyone rushes it at first; the click will tell you.',
    ],
    tempoBpm: 80,
    duration: { kind: 'repetitions', count: 4 },
    notes: threePerStringRun('G', 'major', 3),
  },
  {
    id: 'technique-sweep-triads',
    title: 'Sweep picking — triads across four strings',
    area: 'technique',
    level: 3,
    styles: ['metal', 'rock'],
    techniques: ['sweep'],
    contexts: ['andalusian-cadence'],
    key: 'C',
    tonic: 'A',
    about: [
      'A minor, G, F and E as four-string arpeggios: one continuous downstroke across the strings on the way up, a note added on top, one continuous upstroke on the way back. The pick falls from string to string; it does not make four separate strokes.',
      'The fretting hand does the separating. Each finger lifts as the next note sounds, so the arpeggio never rings like a strummed chord.',
    ],
    tempoBpm: 70,
    duration: { kind: 'repetitions', count: 4 },
    notes: tab('4/7 3/5 2/5 1/5 1/8 1/5 2/5 3/5 | 4/5 3/4 2/3 1/3 1/7 1/3 2/3 3/4 | 4/3 3/2 2/1 1/1 1/5 1/1 2/1 3/2 | 4/2 3/1 2/0 1/0 1/4 1/0 2/0 3/1 | 4/7:4'),
  },
  {
    id: 'technique-gallop',
    title: 'The gallop — an eighth and two sixteenths',
    area: 'technique',
    level: 2,
    styles: ['metal', 'rock'],
    techniques: ['alternate', 'palm-mute'],
    feel: 'straight-16',
    about: [
      'The rhythm under half of heavy metal: long-short-short, picked down, down-up, on the low strings. Rest the edge of the picking hand on the strings at the bridge so the notes thud rather than ring.',
      'The two sixteenths are the hard part: they must be even, and the next long note must not be late. Keep the wrist loose; tension is what slows a gallop down.',
    ],
    tempoBpm: 80,
    duration: { kind: 'repetitions', count: 6 },
    notes: tab(
      '6/0 6/0:0.25*2 6/0 6/0:0.25*2 6/3 6/3:0.25*2 5/0 5/0:0.25*2 | 6/0 6/0:0.25*2 6/0 6/0:0.25*2 6/1 6/1:0.25*2 6/3 6/3:0.25*2 | 6/0:4',
    ),
  },
  {
    id: 'technique-tremolo',
    title: 'Tremolo picking — a melody on one string',
    area: 'technique',
    level: 3,
    styles: ['metal', 'rock', 'latin-flamenco'],
    techniques: ['tremolo', 'single-string', 'position-shift'],
    feel: 'straight-16',
    key: 'G',
    tonic: 'E',
    about: [
      'An E minor melody on the high E string, every note picked four times. Tremolo picking is alternate picking made small: the motion comes from the wrist and the pick barely leaves the string.',
      'The fretting hand changes note exactly on the beat while the picking hand never stops. Listen for the change landing with the click, not a sixteenth late.',
    ],
    tempoBpm: 70,
    duration: { kind: 'repetitions', count: 4 },
    notes: tab('1/0:0.25*4 1/2:0.25*4 1/3:0.25*4 1/5:0.25*4 | 1/7:0.25*4 1/5:0.25*4 1/3:0.25*4 1/2:0.25*4 | 1/0:4'),
  },
  {
    id: 'technique-pima-open-strings',
    title: 'Fingerstyle — p-i-m-a on the open strings',
    area: 'technique',
    level: 1,
    styles: ['classical', 'folk-acoustic'],
    techniques: ['fingerstyle'],
    about: [
      'Thumb, index, middle, ring: p on a bass string, then i, m and a on the G, B and high E. The fretting hand does nothing at all, so everything you hear is the picking hand.',
      'The thumb moves between the three bass strings while the fingers keep their own strings. Plant each finger lightly before it plays and listen for four notes of equal weight.',
    ],
    tempoBpm: 70,
    duration: { kind: 'repetitions', count: 6 },
    notes: tab('6/0 3/0 2/0 1/0 5/0 3/0 2/0 1/0 | 4/0 3/0 2/0 1/0 5/0 3/0 2/0 1/0 | 6/0:4'),
  },
  {
    id: 'technique-travis-pattern',
    title: 'Travis picking — the alternating thumb',
    area: 'technique',
    level: 2,
    styles: ['folk-acoustic', 'country'],
    techniques: ['travis', 'fingerstyle'],
    contexts: ['I-V-vi-IV'],
    key: 'C',
    about: [
      'C, G, A minor, F. The thumb plays every beat, alternating between two bass strings like a bass player; the fingers fill the off-beats on the treble strings. Hold each chord shape down for its whole bar.',
      'The thumb has to become automatic before anything else can happen. Practise until you can hold a conversation while it keeps going — then the fingers are free to play melodies over it.',
    ],
    tempoBpm: 76,
    duration: { kind: 'repetitions', count: 4 },
    notes: tab('5/3 2/1 4/2 3/0 5/3 2/1 4/2 3/0 | 6/3 2/0 4/0 3/0 6/3 2/0 4/0 3/0 | 5/0 2/1 4/2 3/2 5/0 2/1 4/2 3/2 | 4/3 2/1 3/2 1/1 4/3 2/1 3/2 1/1 | 5/3:4'),
  },
  {
    id: 'technique-hybrid-picking',
    title: 'Hybrid picking — pick and fingers together',
    area: 'technique',
    level: 3,
    styles: ['country', 'rock'],
    techniques: ['hybrid'],
    contexts: ['I-IV-V'],
    key: 'A',
    about: [
      'A to D7 and back. The pick plays the D and G strings; the middle finger plucks the B string and the ring finger the high E. The pick never has to jump: each finger is already waiting over its own string.',
      'Snap the plucked notes a little — that pop against the softer picked notes is the sound of country guitar.',
    ],
    tempoBpm: 80,
    duration: { kind: 'repetitions', count: 4 },
    notes: tab('4/7 2/5 3/6 1/5 4/7 2/5 3/6 1/5 | 4/4 2/3 3/5 1/2 4/4 2/3 3/5 1/2 | 4/7 2/5 3/6 1/5 4/7 2/5 3/6 1/5 | 4/7:4'),
  },
  {
    id: 'technique-rest-stroke-arpeggio',
    title: 'Rest-stroke picking — A minor 6 across the strings',
    area: 'technique',
    level: 3,
    styles: ['jazz/gypsy'],
    techniques: ['rest-stroke'],
    key: 'G',
    tonic: 'A',
    about: [
      'The picking of gypsy jazz: every time you move to a new string, play a downstroke, and let the pick come to rest on the string below. Alternate only while you stay on one string. It is what gives an acoustic guitar enough volume to carry over a rhythm section.',
      'A minor 6 — A, C, E, F♯ — is the home chord of the style. Going up, almost every note is a fresh downstroke; feel the weight of the hand fall through the strings.',
    ],
    tempoBpm: 80,
    duration: { kind: 'repetitions', count: 4 },
    notes: arpeggioRun('A', 'm6', { min: 4, max: 8 }),
  },
]
