import type { Lesson } from './types'

/**
 * The lesson pack, written as tabs. Each exercise is a literal series of
 * notes (string, fret, beats) the player renders and steps through; the
 * scale tabs below were produced by `scaleTab` in authoring.ts — one note
 * per eighth, up through the open position and back down.
 */
export const LESSONS: readonly Lesson[] = [
  {
    id: 'scales-major-open',
    title: 'Major scale I — open position',
    area: 'scales',
    level: 1,
    prerequisites: [],
    estimatedMinutes: 6,
    exercises: [
      {
        id: 'scales-major-open-c',
        title: 'C major — open position',
        tempoBpm: 60,
        duration: { kind: 'minutes', minutes: 2 },
        notes: [
          { string: 6, fret: 0, beats: 0.5 },
          { string: 6, fret: 1, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 5, fret: 2, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 3, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 4, beats: 0.5 },
          { string: 2, fret: 0, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 1, fret: 1, beats: 0.5 },
          { string: 1, fret: 3, beats: 0.5 },
          { string: 1, fret: 1, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 2, fret: 0, beats: 0.5 },
          { string: 3, fret: 4, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 4, fret: 3, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 5, fret: 2, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 6, fret: 1, beats: 0.5 },
          { string: 6, fret: 0, beats: 0.5 },
        ],
      },
      {
        id: 'scales-major-open-g',
        title: 'G major — open position',
        tempoBpm: 60,
        duration: { kind: 'minutes', minutes: 2 },
        notes: [
          { string: 6, fret: 0, beats: 0.5 },
          { string: 6, fret: 2, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 5, fret: 2, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 4, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 4, beats: 0.5 },
          { string: 2, fret: 0, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 1, fret: 2, beats: 0.5 },
          { string: 1, fret: 3, beats: 0.5 },
          { string: 1, fret: 2, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 2, fret: 0, beats: 0.5 },
          { string: 3, fret: 4, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 4, fret: 4, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 5, fret: 2, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 6, fret: 2, beats: 0.5 },
          { string: 6, fret: 0, beats: 0.5 },
        ],
      },
      {
        id: 'scales-major-open-f',
        title: 'F major — open position',
        tempoBpm: 60,
        duration: { kind: 'minutes', minutes: 2 },
        notes: [
          { string: 6, fret: 0, beats: 0.5 },
          { string: 6, fret: 1, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 5, fret: 1, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 3, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 3, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 1, fret: 1, beats: 0.5 },
          { string: 1, fret: 3, beats: 0.5 },
          { string: 1, fret: 1, beats: 0.5 },
          { string: 1, fret: 0, beats: 0.5 },
          { string: 2, fret: 3, beats: 0.5 },
          { string: 2, fret: 1, beats: 0.5 },
          { string: 3, fret: 3, beats: 0.5 },
          { string: 3, fret: 2, beats: 0.5 },
          { string: 3, fret: 0, beats: 0.5 },
          { string: 4, fret: 3, beats: 0.5 },
          { string: 4, fret: 2, beats: 0.5 },
          { string: 4, fret: 0, beats: 0.5 },
          { string: 5, fret: 3, beats: 0.5 },
          { string: 5, fret: 1, beats: 0.5 },
          { string: 5, fret: 0, beats: 0.5 },
          { string: 6, fret: 3, beats: 0.5 },
          { string: 6, fret: 1, beats: 0.5 },
          { string: 6, fret: 0, beats: 0.5 },
        ],
      },
    ],
  },
]

